"""create initial schema

Revision ID: 31ca30cfedb6
Revises: 
Create Date: 2025-12-16 09:51:21.062111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ca30cfedb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usr_users',
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('usr_first_name', sa.String(length=100), nullable=False),
    sa.Column('usr_last_name', sa.String(length=100), nullable=False),
    sa.Column('usr_phone', sa.String(length=20), nullable=True),
    sa.Column('usr_email', sa.String(length=80), nullable=False),
    sa.Column('usr_password', sa.String(length=255), nullable=False),
    sa.Column('usr_email_verified', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('usr_user_active', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('usr_id'),
    sa.UniqueConstraint('usr_email')
    )
    op.create_index(op.f('ix_usr_users_usr_id'), 'usr_users', ['usr_id'], unique=False)
    op.create_table('ect_email_confirmation_token',
    sa.Column('ect_id', sa.Integer(), nullable=False),
    sa.Column('ect_user_id', sa.Integer(), nullable=False),
    sa.Column('ect_hash_token', sa.String(length=255), nullable=False),
    sa.Column('ect_expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ect_user_id'], ['usr_users.usr_id'], ),
    sa.PrimaryKeyConstraint('ect_id')
    )
    op.create_index(op.f('ix_ect_email_confirmation_token_ect_hash_token'), 'ect_email_confirmation_token', ['ect_hash_token'], unique=False)
    op.create_index(op.f('ix_ect_email_confirmation_token_ect_id'), 'ect_email_confirmation_token', ['ect_id'], unique=False)
    op.create_table('psc_password_reset_codes',
    sa.Column('psc_id', sa.Integer(), nullable=False),
    sa.Column('psc_user_id', sa.Integer(), nullable=False),
    sa.Column('psc_code', sa.String(length=6), nullable=False),
    sa.Column('psc_expires_at', sa.DateTime(), nullable=False),
    sa.Column('psc_used_at', sa.DateTime(), nullable=False),
    sa.Column('psc_created_at', sa.DateTime(), nullable=False),
    sa.Column('psc_reset_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['psc_user_id'], ['usr_users.usr_id'], ),
    sa.PrimaryKeyConstraint('psc_id')
    )
    op.create_index(op.f('ix_psc_password_reset_codes_psc_id'), 'psc_password_reset_codes', ['psc_id'], unique=False)
    op.create_index(op.f('ix_psc_password_reset_codes_psc_reset_id'), 'psc_password_reset_codes', ['psc_reset_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_psc_password_reset_codes_psc_reset_id'), table_name='psc_password_reset_codes')
    op.drop_index(op.f('ix_psc_password_reset_codes_psc_id'), table_name='psc_password_reset_codes')
    op.drop_table('psc_password_reset_codes')
    op.drop_index(op.f('ix_ect_email_confirmation_token_ect_id'), table_name='ect_email_confirmation_token')
    op.drop_index(op.f('ix_ect_email_confirmation_token_ect_hash_token'), table_name='ect_email_confirmation_token')
    op.drop_table('ect_email_confirmation_token')
    op.drop_index(op.f('ix_usr_users_usr_id'), table_name='usr_users')
    op.drop_table('usr_users')
    # ### end Alembic commands ###
